INSERT INTO USER (USER_NAME, EMAIL, IMAGE, PASSWORD) VALUES ('admin', 'admin@budgetkeeper.ru', NULL, 'password123');
INSERT INTO USER (USER_NAME, EMAIL, IMAGE, PASSWORD) VALUES ('User1', 'email1@mail.ru', NULL, 'password1');
INSERT INTO USER (USER_NAME, EMAIL, IMAGE, PASSWORD) VALUES ('User2', 'email2@mail.ru', NULL, 'password2');
INSERT INTO USER (USER_NAME, EMAIL, IMAGE, PASSWORD) VALUES ('User3', 'email3@mail.ru', NULL, 'password3');
INSERT INTO USER (USER_NAME, EMAIL, IMAGE, PASSWORD) VALUES ('User4', 'email4@mail.ru', NULL, 'password4');
INSERT INTO USER (USER_NAME, EMAIL, IMAGE, PASSWORD) VALUES ('User5', 'email5@mail.ru', NULL, 'password5');

INSERT INTO ACCOUNT (ACCOUNT_ID, TYPE, AMOUNT, USER_NAME) VALUES (1, 'CASH', 1000, 'User1');
INSERT INTO ACCOUNT (ACCOUNT_ID, TYPE, AMOUNT, USER_NAME) VALUES (2, 'CASH', 1000, 'User1');
INSERT INTO ACCOUNT (ACCOUNT_ID, TYPE, AMOUNT, USER_NAME) VALUES (3, 'CASH', 1000, 'User2');
INSERT INTO ACCOUNT (ACCOUNT_ID, TYPE, AMOUNT, USER_NAME) VALUES (4, 'CASH', 1000, 'User2');
INSERT INTO ACCOUNT (ACCOUNT_ID, TYPE, AMOUNT, USER_NAME) VALUES (5, 'CASH', 1000, 'User3');
INSERT INTO ACCOUNT (ACCOUNT_ID, TYPE, AMOUNT, USER_NAME) VALUES (6, 'CASH', 1000, 'User3');

INSERT INTO USER_ROLES (USER_ROLE_ID, USER_NAME, ROLE) VALUES (1, 'admin', 'ADMIN');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (1, 'some cool category 1');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (2, 'some cool category 2');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (3, 'some cool category 3');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (4, 'some cool category 4');


